meta_path: "/home/jottensmeier/BioAdHoc/Projects/DICE-LUNG/cTWAS/1_workflow/config/meta_gtex_49.tsv"
OUT: "/home/jottensmeier/BioAdHoc/Projects/DICE-LUNG/cTWAS/test_smk_single2"
workdir: "/mnt/hpcscratch/jottensmeier/ctwas"
expression_weights: "/home/jottensmeier/BioAdHoc/Projects/DICE-LUNG/cTWAS/data/Prediction_models/PredixcanV8/mashr_eqtl"
REGIONS_PATH: "/mnt/biohome/jottensmeier/miniforge3/envs/cTWAS/lib/R/library/ctwas/extdata/ldetect/EUR.b38.ldetect.regions.RDS"
LD_DIRS: "/home/jottensmeier/BioAdHoc/Projects/DICE-LUNG/cTWAS/data/LD_reference/LD_BioBank/"
GWAS_path: "/home/jottensmeier/BioAdHoc/Projects/DICE-LUNG/cTWAS/data/GWAS_UKBIOB"
